version: '3'
services:
  tcp_server:
    build: .
    working_dir: /usr/src/app/server
    command: python3 main.py
    volumes:
      - .:/usr/src/app
    ports:
      - "9999:9999"
    restart: always